exclude: ".yarn/|yarn.lock"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: file-contents-sorter
        args: [--ignore-case, --unique]
        files: requirements-to-freeze.txt
  - repo: local
    hooks:
      - id: django-check
        name: django check
        entry: venv/bin/python manage.py check
        pass_filenames: false
        language: system
        always_run: true
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.16.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        args: [--fix]
        types_or: [css, scss, javascript]
        verbose: true
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - eslint-config-preact
          - eslint-plugin-compat
          - eslint-plugin-jest
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - "@babel/core"
          - "@babel/eslint-parser"
          - "@babel/preset-env"
          - "@babel/preset-react"
          - "@babel/plugin-syntax-class-properties"
          - "@babel/plugin-syntax-decorators"
          - "@babel/plugin-syntax-jsx"
          - jest
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: [--list-different, --no-semi]
        types_or: [css, scss, javascript]
        exclude: "^conf/|.*\\.html$|.*\\.json$"
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 1.7.0
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.16
    hooks:
      - id: validate-pyproject
