exclude: ".yarn/|yarn.lock|workbench/static/workbench/lib"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: file-contents-sorter
        args: [--ignore-case, --unique]
        files: requirements-to-freeze.txt
  - repo: local
    hooks:
      - id: django-check
        name: django check
        entry: .venv/bin/python manage.py check
        pass_filenames: false
        language: system
        always_run: true
      - id: prettier
        name: prettier
        entry: npx prettier@3.3.3 --no-semi --write
        language: system
        types_or: [css, scss]
        require_serial: true
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.21.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.1"]
  -   repo: https://github.com/adamchainz/djade-pre-commit
      rev: "1.1.1"
      hooks:
      -   id: djade
          args: [--target-version, "5.1"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.8"
    hooks:
      - id: ruff
        args: [--unsafe-fixes]
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 2.2.4
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.20.2
    hooks:
      - id: validate-pyproject
  - repo: https://github.com/biomejs/pre-commit
    rev: "v0.5.0"
    hooks:
      - id: biome-check
        additional_dependencies: ["@biomejs/biome@1.9.2"]
        args: [--unsafe]
        types_or: [javascript, json]
  - repo: https://github.com/boidolr/pre-commit-images
    rev: v1.8.1
    hooks:
      - id: optimize-avif
      - id: optimize-jpg
      - id: optimize-png
      - id: optimize-svg
      - id: optimize-webp
